// Generated by @opencode-ai/httpapi-codegen. Do not edit.
import { Effect, Stream, Schema } from "effect"
import { Sse } from "effect/unstable/encoding"
import { HttpClientError } from "effect/unstable/http"
import { HttpApiClient } from "effect/unstable/httpapi"
import { ClientApi } from "../contract"
import { ClientError } from "./client-error"

type RawClient = HttpApiClient.ForApi<typeof ClientApi>

const mapClientError = <E>(error: E) =>
  HttpClientError.isHttpClientError(error) || Schema.isSchemaError(error) || Sse.Retry.is(error)
    ? new ClientError({ cause: error })
    : error

const Endpoint0_0 = (raw: RawClient["server.health"]) => () =>
  raw["health.get"]({}).pipe(Effect.mapError(mapClientError))

const adaptGroup0 = (raw: RawClient["server.health"]) => ({ get: Endpoint0_0(raw) })

type Endpoint1_0Request = Parameters<RawClient["server.location"]["location.get"]>[0]
type Endpoint1_0Input = { readonly location?: Endpoint1_0Request["query"]["location"] }
const Endpoint1_0 = (raw: RawClient["server.location"]) => (input?: Endpoint1_0Input) =>
  raw["location.get"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup1 = (raw: RawClient["server.location"]) => ({ get: Endpoint1_0(raw) })

type Endpoint2_0Request = Parameters<RawClient["server.agent"]["agent.list"]>[0]
type Endpoint2_0Input = { readonly location?: Endpoint2_0Request["query"]["location"] }
const Endpoint2_0 = (raw: RawClient["server.agent"]) => (input?: Endpoint2_0Input) =>
  raw["agent.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup2 = (raw: RawClient["server.agent"]) => ({ list: Endpoint2_0(raw) })

type Endpoint3_0Request = Parameters<RawClient["server.session"]["session.list"]>[0]
type Endpoint3_0Input = {
  readonly workspace?: Endpoint3_0Request["query"]["workspace"]
  readonly limit?: Endpoint3_0Request["query"]["limit"]
  readonly order?: Endpoint3_0Request["query"]["order"]
  readonly search?: Endpoint3_0Request["query"]["search"]
  readonly lifecycle?: Endpoint3_0Request["query"]["lifecycle"]
  readonly directory?: Endpoint3_0Request["query"]["directory"]
  readonly project?: Endpoint3_0Request["query"]["project"]
  readonly subpath?: Endpoint3_0Request["query"]["subpath"]
  readonly cursor?: Endpoint3_0Request["query"]["cursor"]
}
const Endpoint3_0 = (raw: RawClient["server.session"]) => (input?: Endpoint3_0Input) =>
  raw["session.list"]({
    query: {
      workspace: input?.["workspace"],
      limit: input?.["limit"],
      order: input?.["order"],
      search: input?.["search"],
      lifecycle: input?.["lifecycle"],
      directory: input?.["directory"],
      project: input?.["project"],
      subpath: input?.["subpath"],
      cursor: input?.["cursor"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint3_1Request = Parameters<RawClient["server.session"]["session.create"]>[0]
type Endpoint3_1Input = {
  readonly id?: Endpoint3_1Request["payload"]["id"]
  readonly agent?: Endpoint3_1Request["payload"]["agent"]
  readonly model?: Endpoint3_1Request["payload"]["model"]
  readonly location?: Endpoint3_1Request["payload"]["location"]
}
const Endpoint3_1 = (raw: RawClient["server.session"]) => (input?: Endpoint3_1Input) =>
  raw["session.create"]({
    payload: { id: input?.["id"], agent: input?.["agent"], model: input?.["model"], location: input?.["location"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const Endpoint3_2 = (raw: RawClient["server.session"]) => () =>
  raw["session.active"]({}).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_3Request = Parameters<RawClient["server.session"]["session.get"]>[0]
type Endpoint3_3Input = { readonly sessionID: Endpoint3_3Request["params"]["sessionID"] }
const Endpoint3_3 = (raw: RawClient["server.session"]) => (input: Endpoint3_3Input) =>
  raw["session.get"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_4Request = Parameters<RawClient["server.session"]["session.tombstone"]>[0]
type Endpoint3_4Input = { readonly sessionID: Endpoint3_4Request["params"]["sessionID"] }
const Endpoint3_4 = (raw: RawClient["server.session"]) => (input: Endpoint3_4Input) =>
  raw["session.tombstone"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_5Request = Parameters<RawClient["server.session"]["session.archive"]>[0]
type Endpoint3_5Input = {
  readonly sessionID: Endpoint3_5Request["params"]["sessionID"]
  readonly requestID: Endpoint3_5Request["payload"]["requestID"]
  readonly expectedLifecycleRevision?: Endpoint3_5Request["payload"]["expectedLifecycleRevision"]
}
const Endpoint3_5 = (raw: RawClient["server.session"]) => (input: Endpoint3_5Input) =>
  raw["session.archive"]({
    params: { sessionID: input["sessionID"] },
    payload: { requestID: input["requestID"], expectedLifecycleRevision: input["expectedLifecycleRevision"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_6Request = Parameters<RawClient["server.session"]["session.restore"]>[0]
type Endpoint3_6Input = {
  readonly sessionID: Endpoint3_6Request["params"]["sessionID"]
  readonly requestID: Endpoint3_6Request["payload"]["requestID"]
  readonly expectedLifecycleRevision?: Endpoint3_6Request["payload"]["expectedLifecycleRevision"]
}
const Endpoint3_6 = (raw: RawClient["server.session"]) => (input: Endpoint3_6Input) =>
  raw["session.restore"]({
    params: { sessionID: input["sessionID"] },
    payload: { requestID: input["requestID"], expectedLifecycleRevision: input["expectedLifecycleRevision"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_7Request = Parameters<RawClient["server.session"]["session.trash"]>[0]
type Endpoint3_7Input = {
  readonly sessionID: Endpoint3_7Request["params"]["sessionID"]
  readonly requestID: Endpoint3_7Request["payload"]["requestID"]
  readonly expectedLifecycleRevision?: Endpoint3_7Request["payload"]["expectedLifecycleRevision"]
}
const Endpoint3_7 = (raw: RawClient["server.session"]) => (input: Endpoint3_7Input) =>
  raw["session.trash"]({
    params: { sessionID: input["sessionID"] },
    payload: { requestID: input["requestID"], expectedLifecycleRevision: input["expectedLifecycleRevision"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_8Request = Parameters<RawClient["server.session"]["session.restoreFromTrash"]>[0]
type Endpoint3_8Input = {
  readonly sessionID: Endpoint3_8Request["params"]["sessionID"]
  readonly requestID: Endpoint3_8Request["payload"]["requestID"]
  readonly expectedLifecycleRevision?: Endpoint3_8Request["payload"]["expectedLifecycleRevision"]
}
const Endpoint3_8 = (raw: RawClient["server.session"]) => (input: Endpoint3_8Input) =>
  raw["session.restoreFromTrash"]({
    params: { sessionID: input["sessionID"] },
    payload: { requestID: input["requestID"], expectedLifecycleRevision: input["expectedLifecycleRevision"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_9Request = Parameters<RawClient["server.session"]["session.purge"]>[0]
type Endpoint3_9Input = {
  readonly sessionID: Endpoint3_9Request["params"]["sessionID"]
  readonly requestID: Endpoint3_9Request["payload"]["requestID"]
  readonly confirmation: Endpoint3_9Request["payload"]["confirmation"]
}
const Endpoint3_9 = (raw: RawClient["server.session"]) => (input: Endpoint3_9Input) =>
  raw["session.purge"]({
    params: { sessionID: input["sessionID"] },
    payload: { requestID: input["requestID"], confirmation: input["confirmation"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_10Request = Parameters<RawClient["server.session"]["session.switchAgent"]>[0]
type Endpoint3_10Input = {
  readonly sessionID: Endpoint3_10Request["params"]["sessionID"]
  readonly agent: Endpoint3_10Request["payload"]["agent"]
}
const Endpoint3_10 = (raw: RawClient["server.session"]) => (input: Endpoint3_10Input) =>
  raw["session.switchAgent"]({ params: { sessionID: input["sessionID"] }, payload: { agent: input["agent"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint3_11Request = Parameters<RawClient["server.session"]["session.switchModel"]>[0]
type Endpoint3_11Input = {
  readonly sessionID: Endpoint3_11Request["params"]["sessionID"]
  readonly model: Endpoint3_11Request["payload"]["model"]
}
const Endpoint3_11 = (raw: RawClient["server.session"]) => (input: Endpoint3_11Input) =>
  raw["session.switchModel"]({ params: { sessionID: input["sessionID"] }, payload: { model: input["model"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint3_12Request = Parameters<RawClient["server.session"]["session.prompt"]>[0]
type Endpoint3_12Input = {
  readonly sessionID: Endpoint3_12Request["params"]["sessionID"]
  readonly id?: Endpoint3_12Request["payload"]["id"]
  readonly prompt: Endpoint3_12Request["payload"]["prompt"]
  readonly delivery?: Endpoint3_12Request["payload"]["delivery"]
  readonly resume?: Endpoint3_12Request["payload"]["resume"]
}
const Endpoint3_12 = (raw: RawClient["server.session"]) => (input: Endpoint3_12Input) =>
  raw["session.prompt"]({
    params: { sessionID: input["sessionID"] },
    payload: { id: input["id"], prompt: input["prompt"], delivery: input["delivery"], resume: input["resume"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_13Request = Parameters<RawClient["server.session"]["session.compact"]>[0]
type Endpoint3_13Input = { readonly sessionID: Endpoint3_13Request["params"]["sessionID"] }
const Endpoint3_13 = (raw: RawClient["server.session"]) => (input: Endpoint3_13Input) =>
  raw["session.compact"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_14Request = Parameters<RawClient["server.session"]["session.wait"]>[0]
type Endpoint3_14Input = { readonly sessionID: Endpoint3_14Request["params"]["sessionID"] }
const Endpoint3_14 = (raw: RawClient["server.session"]) => (input: Endpoint3_14Input) =>
  raw["session.wait"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_15Request = Parameters<RawClient["server.session"]["session.revert.stage"]>[0]
type Endpoint3_15Input = {
  readonly sessionID: Endpoint3_15Request["params"]["sessionID"]
  readonly messageID: Endpoint3_15Request["payload"]["messageID"]
  readonly files?: Endpoint3_15Request["payload"]["files"]
}
const Endpoint3_15 = (raw: RawClient["server.session"]) => (input: Endpoint3_15Input) =>
  raw["session.revert.stage"]({
    params: { sessionID: input["sessionID"] },
    payload: { messageID: input["messageID"], files: input["files"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_16Request = Parameters<RawClient["server.session"]["session.revert.clear"]>[0]
type Endpoint3_16Input = { readonly sessionID: Endpoint3_16Request["params"]["sessionID"] }
const Endpoint3_16 = (raw: RawClient["server.session"]) => (input: Endpoint3_16Input) =>
  raw["session.revert.clear"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_17Request = Parameters<RawClient["server.session"]["session.revert.commit"]>[0]
type Endpoint3_17Input = { readonly sessionID: Endpoint3_17Request["params"]["sessionID"] }
const Endpoint3_17 = (raw: RawClient["server.session"]) => (input: Endpoint3_17Input) =>
  raw["session.revert.commit"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_18Request = Parameters<RawClient["server.session"]["session.context"]>[0]
type Endpoint3_18Input = { readonly sessionID: Endpoint3_18Request["params"]["sessionID"] }
const Endpoint3_18 = (raw: RawClient["server.session"]) => (input: Endpoint3_18Input) =>
  raw["session.context"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_19Request = Parameters<RawClient["server.session"]["session.history"]>[0]
type Endpoint3_19Input = {
  readonly sessionID: Endpoint3_19Request["params"]["sessionID"]
  readonly limit?: Endpoint3_19Request["query"]["limit"]
  readonly after?: Endpoint3_19Request["query"]["after"]
}
const Endpoint3_19 = (raw: RawClient["server.session"]) => (input: Endpoint3_19Input) =>
  raw["session.history"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], after: input["after"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint3_20Request = Parameters<RawClient["server.session"]["session.events"]>[0]
type Endpoint3_20Input = {
  readonly sessionID: Endpoint3_20Request["params"]["sessionID"]
  readonly after?: Endpoint3_20Request["query"]["after"]
}
const Endpoint3_20 = (raw: RawClient["server.session"]) => (input: Endpoint3_20Input) =>
  Stream.unwrap(
    raw["session.events"]({ params: { sessionID: input["sessionID"] }, query: { after: input["after"] } }).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

type Endpoint3_21Request = Parameters<RawClient["server.session"]["session.interrupt"]>[0]
type Endpoint3_21Input = { readonly sessionID: Endpoint3_21Request["params"]["sessionID"] }
const Endpoint3_21 = (raw: RawClient["server.session"]) => (input: Endpoint3_21Input) =>
  raw["session.interrupt"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_22Request = Parameters<RawClient["server.session"]["session.message"]>[0]
type Endpoint3_22Input = {
  readonly sessionID: Endpoint3_22Request["params"]["sessionID"]
  readonly messageID: Endpoint3_22Request["params"]["messageID"]
}
const Endpoint3_22 = (raw: RawClient["server.session"]) => (input: Endpoint3_22Input) =>
  raw["session.message"]({ params: { sessionID: input["sessionID"], messageID: input["messageID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const adaptGroup3 = (raw: RawClient["server.session"]) => ({
  list: Endpoint3_0(raw),
  create: Endpoint3_1(raw),
  active: Endpoint3_2(raw),
  get: Endpoint3_3(raw),
  tombstone: Endpoint3_4(raw),
  archive: Endpoint3_5(raw),
  restore: Endpoint3_6(raw),
  trash: Endpoint3_7(raw),
  restoreFromTrash: Endpoint3_8(raw),
  purge: Endpoint3_9(raw),
  switchAgent: Endpoint3_10(raw),
  switchModel: Endpoint3_11(raw),
  prompt: Endpoint3_12(raw),
  compact: Endpoint3_13(raw),
  wait: Endpoint3_14(raw),
  stage: Endpoint3_15(raw),
  clear: Endpoint3_16(raw),
  commit: Endpoint3_17(raw),
  context: Endpoint3_18(raw),
  history: Endpoint3_19(raw),
  events: Endpoint3_20(raw),
  interrupt: Endpoint3_21(raw),
  message: Endpoint3_22(raw),
})

type Endpoint4_0Request = Parameters<RawClient["server.goal"]["session.goal.get"]>[0]
type Endpoint4_0Input = { readonly sessionID: Endpoint4_0Request["params"]["sessionID"] }
const Endpoint4_0 = (raw: RawClient["server.goal"]) => (input: Endpoint4_0Input) =>
  raw["session.goal.get"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_1Request = Parameters<RawClient["server.goal"]["session.goal.update"]>[0]
type Endpoint4_1Input = {
  readonly sessionID: Endpoint4_1Request["params"]["sessionID"]
  readonly objective: Endpoint4_1Request["payload"]["objective"]
  readonly acceptanceCriteria: Endpoint4_1Request["payload"]["acceptanceCriteria"]
  readonly constraints: Endpoint4_1Request["payload"]["constraints"]
  readonly sourceMessageIDs: Endpoint4_1Request["payload"]["sourceMessageIDs"]
  readonly expectedVersion?: Endpoint4_1Request["payload"]["expectedVersion"]
}
const Endpoint4_1 = (raw: RawClient["server.goal"]) => (input: Endpoint4_1Input) =>
  raw["session.goal.update"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      objective: input["objective"],
      acceptanceCriteria: input["acceptanceCriteria"],
      constraints: input["constraints"],
      sourceMessageIDs: input["sourceMessageIDs"],
      expectedVersion: input["expectedVersion"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_2Request = Parameters<RawClient["server.goal"]["session.goal.status"]>[0]
type Endpoint4_2Input = {
  readonly sessionID: Endpoint4_2Request["params"]["sessionID"]
  readonly status: Endpoint4_2Request["payload"]["status"]
  readonly expectedVersion?: Endpoint4_2Request["payload"]["expectedVersion"]
}
const Endpoint4_2 = (raw: RawClient["server.goal"]) => (input: Endpoint4_2Input) =>
  raw["session.goal.status"]({
    params: { sessionID: input["sessionID"] },
    payload: { status: input["status"], expectedVersion: input["expectedVersion"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const adaptGroup4 = (raw: RawClient["server.goal"]) => ({
  get: Endpoint4_0(raw),
  update: Endpoint4_1(raw),
  status: Endpoint4_2(raw),
})

type Endpoint5_0Request = Parameters<RawClient["server.ledger"]["session.ledger.list"]>[0]
type Endpoint5_0Input = {
  readonly sessionID: Endpoint5_0Request["params"]["sessionID"]
  readonly status?: Endpoint5_0Request["query"]["status"]
}
const Endpoint5_0 = (raw: RawClient["server.ledger"]) => (input: Endpoint5_0Input) =>
  raw["session.ledger.list"]({ params: { sessionID: input["sessionID"] }, query: { status: input["status"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint5_1Request = Parameters<RawClient["server.ledger"]["session.ledger.add"]>[0]
type Endpoint5_1Input = {
  readonly sessionID: Endpoint5_1Request["params"]["sessionID"]
  readonly kind: Endpoint5_1Request["payload"]["kind"]
  readonly text: Endpoint5_1Request["payload"]["text"]
  readonly sourceMessageIDs: Endpoint5_1Request["payload"]["sourceMessageIDs"]
}
const Endpoint5_1 = (raw: RawClient["server.ledger"]) => (input: Endpoint5_1Input) =>
  raw["session.ledger.add"]({
    params: { sessionID: input["sessionID"] },
    payload: { kind: input["kind"], text: input["text"], sourceMessageIDs: input["sourceMessageIDs"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint5_2Request = Parameters<RawClient["server.ledger"]["session.ledger.supersede"]>[0]
type Endpoint5_2Input = {
  readonly sessionID: Endpoint5_2Request["params"]["sessionID"]
  readonly entryID: Endpoint5_2Request["params"]["entryID"]
  readonly supersededBy: Endpoint5_2Request["payload"]["supersededBy"]
}
const Endpoint5_2 = (raw: RawClient["server.ledger"]) => (input: Endpoint5_2Input) =>
  raw["session.ledger.supersede"]({
    params: { sessionID: input["sessionID"], entryID: input["entryID"] },
    payload: { supersededBy: input["supersededBy"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup5 = (raw: RawClient["server.ledger"]) => ({
  list: Endpoint5_0(raw),
  add: Endpoint5_1(raw),
  supersede: Endpoint5_2(raw),
})

type Endpoint6_0Request = Parameters<RawClient["server.history"]["session.history.search"]>[0]
type Endpoint6_0Input = {
  readonly sessionID: Endpoint6_0Request["params"]["sessionID"]
  readonly query: Endpoint6_0Request["query"]["query"]
  readonly limit?: Endpoint6_0Request["query"]["limit"]
}
const Endpoint6_0 = (raw: RawClient["server.history"]) => (input: Endpoint6_0Input) =>
  raw["session.history.search"]({
    params: { sessionID: input["sessionID"] },
    query: { query: input["query"], limit: input["limit"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint6_1Request = Parameters<RawClient["server.history"]["session.history.get"]>[0]
type Endpoint6_1Input = {
  readonly sessionID: Endpoint6_1Request["params"]["sessionID"]
  readonly messageID: Endpoint6_1Request["params"]["messageID"]
  readonly before?: Endpoint6_1Request["query"]["before"]
  readonly after?: Endpoint6_1Request["query"]["after"]
}
const Endpoint6_1 = (raw: RawClient["server.history"]) => (input: Endpoint6_1Input) =>
  raw["session.history.get"]({
    params: { sessionID: input["sessionID"], messageID: input["messageID"] },
    query: { before: input["before"], after: input["after"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const adaptGroup6 = (raw: RawClient["server.history"]) => ({ search: Endpoint6_0(raw), get: Endpoint6_1(raw) })

type Endpoint7_0Request = Parameters<RawClient["server.message"]["session.messages"]>[0]
type Endpoint7_0Input = {
  readonly sessionID: Endpoint7_0Request["params"]["sessionID"]
  readonly limit?: Endpoint7_0Request["query"]["limit"]
  readonly order?: Endpoint7_0Request["query"]["order"]
  readonly cursor?: Endpoint7_0Request["query"]["cursor"]
}
const Endpoint7_0 = (raw: RawClient["server.message"]) => (input: Endpoint7_0Input) =>
  raw["session.messages"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], order: input["order"], cursor: input["cursor"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup7 = (raw: RawClient["server.message"]) => ({ list: Endpoint7_0(raw) })

type Endpoint8_0Request = Parameters<RawClient["server.model"]["model.list"]>[0]
type Endpoint8_0Input = { readonly location?: Endpoint8_0Request["query"]["location"] }
const Endpoint8_0 = (raw: RawClient["server.model"]) => (input?: Endpoint8_0Input) =>
  raw["model.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup8 = (raw: RawClient["server.model"]) => ({ list: Endpoint8_0(raw) })

type Endpoint9_0Request = Parameters<RawClient["server.provider"]["provider.list"]>[0]
type Endpoint9_0Input = { readonly location?: Endpoint9_0Request["query"]["location"] }
const Endpoint9_0 = (raw: RawClient["server.provider"]) => (input?: Endpoint9_0Input) =>
  raw["provider.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint9_1Request = Parameters<RawClient["server.provider"]["provider.get"]>[0]
type Endpoint9_1Input = {
  readonly providerID: Endpoint9_1Request["params"]["providerID"]
  readonly location?: Endpoint9_1Request["query"]["location"]
}
const Endpoint9_1 = (raw: RawClient["server.provider"]) => (input: Endpoint9_1Input) =>
  raw["provider.get"]({ params: { providerID: input["providerID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup9 = (raw: RawClient["server.provider"]) => ({ list: Endpoint9_0(raw), get: Endpoint9_1(raw) })

type Endpoint10_0Request = Parameters<RawClient["server.integration"]["integration.list"]>[0]
type Endpoint10_0Input = { readonly location?: Endpoint10_0Request["query"]["location"] }
const Endpoint10_0 = (raw: RawClient["server.integration"]) => (input?: Endpoint10_0Input) =>
  raw["integration.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint10_1Request = Parameters<RawClient["server.integration"]["integration.get"]>[0]
type Endpoint10_1Input = {
  readonly integrationID: Endpoint10_1Request["params"]["integrationID"]
  readonly location?: Endpoint10_1Request["query"]["location"]
}
const Endpoint10_1 = (raw: RawClient["server.integration"]) => (input: Endpoint10_1Input) =>
  raw["integration.get"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint10_2Request = Parameters<RawClient["server.integration"]["integration.connect.key"]>[0]
type Endpoint10_2Input = {
  readonly integrationID: Endpoint10_2Request["params"]["integrationID"]
  readonly location?: Endpoint10_2Request["query"]["location"]
  readonly key: Endpoint10_2Request["payload"]["key"]
  readonly label?: Endpoint10_2Request["payload"]["label"]
}
const Endpoint10_2 = (raw: RawClient["server.integration"]) => (input: Endpoint10_2Input) =>
  raw["integration.connect.key"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
    payload: { key: input["key"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint10_3Request = Parameters<RawClient["server.integration"]["integration.connect.oauth"]>[0]
type Endpoint10_3Input = {
  readonly integrationID: Endpoint10_3Request["params"]["integrationID"]
  readonly location?: Endpoint10_3Request["query"]["location"]
  readonly methodID: Endpoint10_3Request["payload"]["methodID"]
  readonly inputs: Endpoint10_3Request["payload"]["inputs"]
  readonly label?: Endpoint10_3Request["payload"]["label"]
}
const Endpoint10_3 = (raw: RawClient["server.integration"]) => (input: Endpoint10_3Input) =>
  raw["integration.connect.oauth"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
    payload: { methodID: input["methodID"], inputs: input["inputs"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint10_4Request = Parameters<RawClient["server.integration"]["integration.attempt.status"]>[0]
type Endpoint10_4Input = {
  readonly attemptID: Endpoint10_4Request["params"]["attemptID"]
  readonly location?: Endpoint10_4Request["query"]["location"]
}
const Endpoint10_4 = (raw: RawClient["server.integration"]) => (input: Endpoint10_4Input) =>
  raw["integration.attempt.status"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint10_5Request = Parameters<RawClient["server.integration"]["integration.attempt.complete"]>[0]
type Endpoint10_5Input = {
  readonly attemptID: Endpoint10_5Request["params"]["attemptID"]
  readonly location?: Endpoint10_5Request["query"]["location"]
  readonly code?: Endpoint10_5Request["payload"]["code"]
}
const Endpoint10_5 = (raw: RawClient["server.integration"]) => (input: Endpoint10_5Input) =>
  raw["integration.attempt.complete"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
    payload: { code: input["code"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint10_6Request = Parameters<RawClient["server.integration"]["integration.attempt.cancel"]>[0]
type Endpoint10_6Input = {
  readonly attemptID: Endpoint10_6Request["params"]["attemptID"]
  readonly location?: Endpoint10_6Request["query"]["location"]
}
const Endpoint10_6 = (raw: RawClient["server.integration"]) => (input: Endpoint10_6Input) =>
  raw["integration.attempt.cancel"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup10 = (raw: RawClient["server.integration"]) => ({
  list: Endpoint10_0(raw),
  get: Endpoint10_1(raw),
  connectKey: Endpoint10_2(raw),
  connectOauth: Endpoint10_3(raw),
  attemptStatus: Endpoint10_4(raw),
  attemptComplete: Endpoint10_5(raw),
  attemptCancel: Endpoint10_6(raw),
})

type Endpoint11_0Request = Parameters<RawClient["server.credential"]["credential.update"]>[0]
type Endpoint11_0Input = {
  readonly credentialID: Endpoint11_0Request["params"]["credentialID"]
  readonly location?: Endpoint11_0Request["query"]["location"]
  readonly label: Endpoint11_0Request["payload"]["label"]
}
const Endpoint11_0 = (raw: RawClient["server.credential"]) => (input: Endpoint11_0Input) =>
  raw["credential.update"]({
    params: { credentialID: input["credentialID"] },
    query: { location: input["location"] },
    payload: { label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint11_1Request = Parameters<RawClient["server.credential"]["credential.remove"]>[0]
type Endpoint11_1Input = {
  readonly credentialID: Endpoint11_1Request["params"]["credentialID"]
  readonly location?: Endpoint11_1Request["query"]["location"]
}
const Endpoint11_1 = (raw: RawClient["server.credential"]) => (input: Endpoint11_1Input) =>
  raw["credential.remove"]({
    params: { credentialID: input["credentialID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup11 = (raw: RawClient["server.credential"]) => ({ update: Endpoint11_0(raw), remove: Endpoint11_1(raw) })

type Endpoint12_0Request = Parameters<RawClient["server.permission"]["permission.request.list"]>[0]
type Endpoint12_0Input = { readonly location?: Endpoint12_0Request["query"]["location"] }
const Endpoint12_0 = (raw: RawClient["server.permission"]) => (input?: Endpoint12_0Input) =>
  raw["permission.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint12_1Request = Parameters<RawClient["server.permission"]["permission.saved.list"]>[0]
type Endpoint12_1Input = { readonly projectID?: Endpoint12_1Request["query"]["projectID"] }
const Endpoint12_1 = (raw: RawClient["server.permission"]) => (input?: Endpoint12_1Input) =>
  raw["permission.saved.list"]({ query: { projectID: input?.["projectID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint12_2Request = Parameters<RawClient["server.permission"]["permission.saved.remove"]>[0]
type Endpoint12_2Input = { readonly id: Endpoint12_2Request["params"]["id"] }
const Endpoint12_2 = (raw: RawClient["server.permission"]) => (input: Endpoint12_2Input) =>
  raw["permission.saved.remove"]({ params: { id: input["id"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint12_3Request = Parameters<RawClient["server.permission"]["session.permission.create"]>[0]
type Endpoint12_3Input = {
  readonly sessionID: Endpoint12_3Request["params"]["sessionID"]
  readonly id?: Endpoint12_3Request["payload"]["id"]
  readonly action: Endpoint12_3Request["payload"]["action"]
  readonly resources: Endpoint12_3Request["payload"]["resources"]
  readonly save?: Endpoint12_3Request["payload"]["save"]
  readonly metadata?: Endpoint12_3Request["payload"]["metadata"]
  readonly source?: Endpoint12_3Request["payload"]["source"]
  readonly agent?: Endpoint12_3Request["payload"]["agent"]
}
const Endpoint12_3 = (raw: RawClient["server.permission"]) => (input: Endpoint12_3Input) =>
  raw["session.permission.create"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      id: input["id"],
      action: input["action"],
      resources: input["resources"],
      save: input["save"],
      metadata: input["metadata"],
      source: input["source"],
      agent: input["agent"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint12_4Request = Parameters<RawClient["server.permission"]["session.permission.list"]>[0]
type Endpoint12_4Input = { readonly sessionID: Endpoint12_4Request["params"]["sessionID"] }
const Endpoint12_4 = (raw: RawClient["server.permission"]) => (input: Endpoint12_4Input) =>
  raw["session.permission.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint12_5Request = Parameters<RawClient["server.permission"]["session.permission.get"]>[0]
type Endpoint12_5Input = {
  readonly sessionID: Endpoint12_5Request["params"]["sessionID"]
  readonly requestID: Endpoint12_5Request["params"]["requestID"]
}
const Endpoint12_5 = (raw: RawClient["server.permission"]) => (input: Endpoint12_5Input) =>
  raw["session.permission.get"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint12_6Request = Parameters<RawClient["server.permission"]["session.permission.reply"]>[0]
type Endpoint12_6Input = {
  readonly sessionID: Endpoint12_6Request["params"]["sessionID"]
  readonly requestID: Endpoint12_6Request["params"]["requestID"]
  readonly reply: Endpoint12_6Request["payload"]["reply"]
  readonly message?: Endpoint12_6Request["payload"]["message"]
}
const Endpoint12_6 = (raw: RawClient["server.permission"]) => (input: Endpoint12_6Input) =>
  raw["session.permission.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { reply: input["reply"], message: input["message"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup12 = (raw: RawClient["server.permission"]) => ({
  listRequests: Endpoint12_0(raw),
  listSaved: Endpoint12_1(raw),
  removeSaved: Endpoint12_2(raw),
  create: Endpoint12_3(raw),
  list: Endpoint12_4(raw),
  get: Endpoint12_5(raw),
  reply: Endpoint12_6(raw),
})

type Endpoint13_0Request = Parameters<RawClient["server.fs"]["fs.list"]>[0]
type Endpoint13_0Input = {
  readonly location?: Endpoint13_0Request["query"]["location"]
  readonly path?: Endpoint13_0Request["query"]["path"]
}
const Endpoint13_0 = (raw: RawClient["server.fs"]) => (input?: Endpoint13_0Input) =>
  raw["fs.list"]({ query: { location: input?.["location"], path: input?.["path"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint13_1Request = Parameters<RawClient["server.fs"]["fs.find"]>[0]
type Endpoint13_1Input = {
  readonly location?: Endpoint13_1Request["query"]["location"]
  readonly query: Endpoint13_1Request["query"]["query"]
  readonly type?: Endpoint13_1Request["query"]["type"]
  readonly limit?: Endpoint13_1Request["query"]["limit"]
}
const Endpoint13_1 = (raw: RawClient["server.fs"]) => (input: Endpoint13_1Input) =>
  raw["fs.find"]({
    query: { location: input["location"], query: input["query"], type: input["type"], limit: input["limit"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup13 = (raw: RawClient["server.fs"]) => ({ list: Endpoint13_0(raw), find: Endpoint13_1(raw) })

type Endpoint14_0Request = Parameters<RawClient["server.command"]["command.list"]>[0]
type Endpoint14_0Input = { readonly location?: Endpoint14_0Request["query"]["location"] }
const Endpoint14_0 = (raw: RawClient["server.command"]) => (input?: Endpoint14_0Input) =>
  raw["command.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup14 = (raw: RawClient["server.command"]) => ({ list: Endpoint14_0(raw) })

type Endpoint15_0Request = Parameters<RawClient["server.skill"]["skill.list"]>[0]
type Endpoint15_0Input = { readonly location?: Endpoint15_0Request["query"]["location"] }
const Endpoint15_0 = (raw: RawClient["server.skill"]) => (input?: Endpoint15_0Input) =>
  raw["skill.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup15 = (raw: RawClient["server.skill"]) => ({ list: Endpoint15_0(raw) })

const Endpoint16_0 = (raw: RawClient["server.event"]) => () =>
  Stream.unwrap(
    raw["event.subscribe"]({}).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

const adaptGroup16 = (raw: RawClient["server.event"]) => ({ subscribe: Endpoint16_0(raw) })

type Endpoint17_0Request = Parameters<RawClient["server.pty"]["pty.list"]>[0]
type Endpoint17_0Input = { readonly location?: Endpoint17_0Request["query"]["location"] }
const Endpoint17_0 = (raw: RawClient["server.pty"]) => (input?: Endpoint17_0Input) =>
  raw["pty.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint17_1Request = Parameters<RawClient["server.pty"]["pty.create"]>[0]
type Endpoint17_1Input = {
  readonly location?: Endpoint17_1Request["query"]["location"]
  readonly command?: Endpoint17_1Request["payload"]["command"]
  readonly args?: Endpoint17_1Request["payload"]["args"]
  readonly cwd?: Endpoint17_1Request["payload"]["cwd"]
  readonly title?: Endpoint17_1Request["payload"]["title"]
  readonly env?: Endpoint17_1Request["payload"]["env"]
}
const Endpoint17_1 = (raw: RawClient["server.pty"]) => (input?: Endpoint17_1Input) =>
  raw["pty.create"]({
    query: { location: input?.["location"] },
    payload: {
      command: input?.["command"],
      args: input?.["args"],
      cwd: input?.["cwd"],
      title: input?.["title"],
      env: input?.["env"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint17_2Request = Parameters<RawClient["server.pty"]["pty.get"]>[0]
type Endpoint17_2Input = {
  readonly ptyID: Endpoint17_2Request["params"]["ptyID"]
  readonly location?: Endpoint17_2Request["query"]["location"]
}
const Endpoint17_2 = (raw: RawClient["server.pty"]) => (input: Endpoint17_2Input) =>
  raw["pty.get"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint17_3Request = Parameters<RawClient["server.pty"]["pty.update"]>[0]
type Endpoint17_3Input = {
  readonly ptyID: Endpoint17_3Request["params"]["ptyID"]
  readonly location?: Endpoint17_3Request["query"]["location"]
  readonly title?: Endpoint17_3Request["payload"]["title"]
  readonly size?: Endpoint17_3Request["payload"]["size"]
}
const Endpoint17_3 = (raw: RawClient["server.pty"]) => (input: Endpoint17_3Input) =>
  raw["pty.update"]({
    params: { ptyID: input["ptyID"] },
    query: { location: input["location"] },
    payload: { title: input["title"], size: input["size"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint17_4Request = Parameters<RawClient["server.pty"]["pty.remove"]>[0]
type Endpoint17_4Input = {
  readonly ptyID: Endpoint17_4Request["params"]["ptyID"]
  readonly location?: Endpoint17_4Request["query"]["location"]
}
const Endpoint17_4 = (raw: RawClient["server.pty"]) => (input: Endpoint17_4Input) =>
  raw["pty.remove"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup17 = (raw: RawClient["server.pty"]) => ({
  list: Endpoint17_0(raw),
  create: Endpoint17_1(raw),
  get: Endpoint17_2(raw),
  update: Endpoint17_3(raw),
  remove: Endpoint17_4(raw),
})

type Endpoint18_0Request = Parameters<RawClient["server.question"]["question.request.list"]>[0]
type Endpoint18_0Input = { readonly location?: Endpoint18_0Request["query"]["location"] }
const Endpoint18_0 = (raw: RawClient["server.question"]) => (input?: Endpoint18_0Input) =>
  raw["question.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint18_1Request = Parameters<RawClient["server.question"]["session.question.list"]>[0]
type Endpoint18_1Input = { readonly sessionID: Endpoint18_1Request["params"]["sessionID"] }
const Endpoint18_1 = (raw: RawClient["server.question"]) => (input: Endpoint18_1Input) =>
  raw["session.question.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint18_2Request = Parameters<RawClient["server.question"]["session.question.reply"]>[0]
type Endpoint18_2Input = {
  readonly sessionID: Endpoint18_2Request["params"]["sessionID"]
  readonly requestID: Endpoint18_2Request["params"]["requestID"]
  readonly answers: Endpoint18_2Request["payload"]["answers"]
}
const Endpoint18_2 = (raw: RawClient["server.question"]) => (input: Endpoint18_2Input) =>
  raw["session.question.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { answers: input["answers"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint18_3Request = Parameters<RawClient["server.question"]["session.question.reject"]>[0]
type Endpoint18_3Input = {
  readonly sessionID: Endpoint18_3Request["params"]["sessionID"]
  readonly requestID: Endpoint18_3Request["params"]["requestID"]
}
const Endpoint18_3 = (raw: RawClient["server.question"]) => (input: Endpoint18_3Input) =>
  raw["session.question.reject"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup18 = (raw: RawClient["server.question"]) => ({
  listRequests: Endpoint18_0(raw),
  list: Endpoint18_1(raw),
  reply: Endpoint18_2(raw),
  reject: Endpoint18_3(raw),
})

type Endpoint19_0Request = Parameters<RawClient["server.reference"]["reference.list"]>[0]
type Endpoint19_0Input = { readonly location?: Endpoint19_0Request["query"]["location"] }
const Endpoint19_0 = (raw: RawClient["server.reference"]) => (input?: Endpoint19_0Input) =>
  raw["reference.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup19 = (raw: RawClient["server.reference"]) => ({ list: Endpoint19_0(raw) })

type Endpoint20_0Request = Parameters<RawClient["server.projectCopy"]["projectCopy.create"]>[0]
type Endpoint20_0Input = {
  readonly projectID: Endpoint20_0Request["params"]["projectID"]
  readonly location?: Endpoint20_0Request["query"]["location"]
  readonly strategy: Endpoint20_0Request["payload"]["strategy"]
  readonly directory: Endpoint20_0Request["payload"]["directory"]
  readonly name?: Endpoint20_0Request["payload"]["name"]
}
const Endpoint20_0 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint20_0Input) =>
  raw["projectCopy.create"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { strategy: input["strategy"], directory: input["directory"], name: input["name"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint20_1Request = Parameters<RawClient["server.projectCopy"]["projectCopy.remove"]>[0]
type Endpoint20_1Input = {
  readonly projectID: Endpoint20_1Request["params"]["projectID"]
  readonly location?: Endpoint20_1Request["query"]["location"]
  readonly directory: Endpoint20_1Request["payload"]["directory"]
  readonly force: Endpoint20_1Request["payload"]["force"]
}
const Endpoint20_1 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint20_1Input) =>
  raw["projectCopy.remove"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { directory: input["directory"], force: input["force"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint20_2Request = Parameters<RawClient["server.projectCopy"]["projectCopy.refresh"]>[0]
type Endpoint20_2Input = {
  readonly projectID: Endpoint20_2Request["params"]["projectID"]
  readonly location?: Endpoint20_2Request["query"]["location"]
}
const Endpoint20_2 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint20_2Input) =>
  raw["projectCopy.refresh"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup20 = (raw: RawClient["server.projectCopy"]) => ({
  create: Endpoint20_0(raw),
  remove: Endpoint20_1(raw),
  refresh: Endpoint20_2(raw),
})

const Endpoint21_0 = (raw: RawClient["server.project"]) => () =>
  raw["project.list"]({}).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint21_1Request = Parameters<RawClient["server.project"]["project.get"]>[0]
type Endpoint21_1Input = { readonly projectID: Endpoint21_1Request["params"]["projectID"] }
const Endpoint21_1 = (raw: RawClient["server.project"]) => (input: Endpoint21_1Input) =>
  raw["project.get"]({ params: { projectID: input["projectID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint21_2Request = Parameters<RawClient["server.project"]["project.updateMetadata"]>[0]
type Endpoint21_2Input = {
  readonly projectID: Endpoint21_2Request["params"]["projectID"]
  readonly name?: Endpoint21_2Request["payload"]["name"]
  readonly icon?: Endpoint21_2Request["payload"]["icon"]
  readonly commands?: Endpoint21_2Request["payload"]["commands"]
}
const Endpoint21_2 = (raw: RawClient["server.project"]) => (input: Endpoint21_2Input) =>
  raw["project.updateMetadata"]({
    params: { projectID: input["projectID"] },
    payload: { name: input["name"], icon: input["icon"], commands: input["commands"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint21_3Request = Parameters<RawClient["server.project"]["project.preference.read"]>[0]
type Endpoint21_3Input = { readonly projectID: Endpoint21_3Request["params"]["projectID"] }
const Endpoint21_3 = (raw: RawClient["server.project"]) => (input: Endpoint21_3Input) =>
  raw["project.preference.read"]({ params: { projectID: input["projectID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint21_4Request = Parameters<RawClient["server.project"]["project.preference.write"]>[0]
type Endpoint21_4Input = {
  readonly projectID: Endpoint21_4Request["params"]["projectID"]
  readonly favorite?: Endpoint21_4Request["payload"]["favorite"]
  readonly rank?: Endpoint21_4Request["payload"]["rank"]
  readonly hidden?: Endpoint21_4Request["payload"]["hidden"]
  readonly lastOpenedAt?: Endpoint21_4Request["payload"]["lastOpenedAt"]
  readonly expectedRevision?: Endpoint21_4Request["payload"]["expectedRevision"]
}
const Endpoint21_4 = (raw: RawClient["server.project"]) => (input: Endpoint21_4Input) =>
  raw["project.preference.write"]({
    params: { projectID: input["projectID"] },
    payload: {
      favorite: input["favorite"],
      rank: input["rank"],
      hidden: input["hidden"],
      lastOpenedAt: input["lastOpenedAt"],
      expectedRevision: input["expectedRevision"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const adaptGroup21 = (raw: RawClient["server.project"]) => ({
  list: Endpoint21_0(raw),
  get: Endpoint21_1(raw),
  updateMetadata: Endpoint21_2(raw),
  read: Endpoint21_3(raw),
  write: Endpoint21_4(raw),
})

type Endpoint22_0Request = Parameters<RawClient["server.config-document"]["config.document.target.list"]>[0]
type Endpoint22_0Input = { readonly location?: Endpoint22_0Request["query"]["location"] }
const Endpoint22_0 = (raw: RawClient["server.config-document"]) => (input?: Endpoint22_0Input) =>
  raw["config.document.target.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint22_1Request = Parameters<RawClient["server.config-document"]["config.document.target.read"]>[0]
type Endpoint22_1Input = {
  readonly targetID: Endpoint22_1Request["params"]["targetID"]
  readonly location?: Endpoint22_1Request["query"]["location"]
}
const Endpoint22_1 = (raw: RawClient["server.config-document"]) => (input: Endpoint22_1Input) =>
  raw["config.document.target.read"]({
    params: { targetID: input["targetID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint22_2Request = Parameters<RawClient["server.config-document"]["config.document.effective.get"]>[0]
type Endpoint22_2Input = { readonly location?: Endpoint22_2Request["query"]["location"] }
const Endpoint22_2 = (raw: RawClient["server.config-document"]) => (input?: Endpoint22_2Input) =>
  raw["config.document.effective.get"]({ query: { location: input?.["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint22_3Request = Parameters<RawClient["server.config-document"]["config.document.target.validate"]>[0]
type Endpoint22_3Input = {
  readonly targetID: Endpoint22_3Request["params"]["targetID"]
  readonly location?: Endpoint22_3Request["query"]["location"]
  readonly patch: Endpoint22_3Request["payload"]["patch"]
}
const Endpoint22_3 = (raw: RawClient["server.config-document"]) => (input: Endpoint22_3Input) =>
  raw["config.document.target.validate"]({
    params: { targetID: input["targetID"] },
    query: { location: input["location"] },
    payload: { patch: input["patch"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint22_4Request = Parameters<RawClient["server.config-document"]["config.document.target.apply"]>[0]
type Endpoint22_4Input = {
  readonly targetID: Endpoint22_4Request["params"]["targetID"]
  readonly location?: Endpoint22_4Request["query"]["location"]
  readonly expectedHash: Endpoint22_4Request["payload"]["expectedHash"]
  readonly patch: Endpoint22_4Request["payload"]["patch"]
}
const Endpoint22_4 = (raw: RawClient["server.config-document"]) => (input: Endpoint22_4Input) =>
  raw["config.document.target.apply"]({
    params: { targetID: input["targetID"] },
    query: { location: input["location"] },
    payload: { expectedHash: input["expectedHash"], patch: input["patch"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup22 = (raw: RawClient["server.config-document"]) => ({
  targetList: Endpoint22_0(raw),
  targetRead: Endpoint22_1(raw),
  effectiveGet: Endpoint22_2(raw),
  targetValidate: Endpoint22_3(raw),
  targetApply: Endpoint22_4(raw),
})

type Endpoint23_0Request = Parameters<RawClient["server.mcp"]["mcp.list"]>[0]
type Endpoint23_0Input = { readonly location?: Endpoint23_0Request["query"]["location"] }
const Endpoint23_0 = (raw: RawClient["server.mcp"]) => (input?: Endpoint23_0Input) =>
  raw["mcp.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint23_1Request = Parameters<RawClient["server.mcp"]["mcp.status"]>[0]
type Endpoint23_1Input = { readonly location?: Endpoint23_1Request["query"]["location"] }
const Endpoint23_1 = (raw: RawClient["server.mcp"]) => (input?: Endpoint23_1Input) =>
  raw["mcp.status"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup23 = (raw: RawClient["server.mcp"]) => ({ list: Endpoint23_0(raw), status: Endpoint23_1(raw) })

const adaptClient = (raw: RawClient) => ({
  health: adaptGroup0(raw["server.health"]),
  location: adaptGroup1(raw["server.location"]),
  agents: adaptGroup2(raw["server.agent"]),
  sessions: adaptGroup3(raw["server.session"]),
  "server.goal": adaptGroup4(raw["server.goal"]),
  "server.ledger": adaptGroup5(raw["server.ledger"]),
  "server.history": adaptGroup6(raw["server.history"]),
  messages: adaptGroup7(raw["server.message"]),
  models: adaptGroup8(raw["server.model"]),
  providers: adaptGroup9(raw["server.provider"]),
  integrations: adaptGroup10(raw["server.integration"]),
  credentials: adaptGroup11(raw["server.credential"]),
  permissions: adaptGroup12(raw["server.permission"]),
  files: adaptGroup13(raw["server.fs"]),
  commands: adaptGroup14(raw["server.command"]),
  skills: adaptGroup15(raw["server.skill"]),
  events: adaptGroup16(raw["server.event"]),
  ptys: adaptGroup17(raw["server.pty"]),
  questions: adaptGroup18(raw["server.question"]),
  references: adaptGroup19(raw["server.reference"]),
  projectCopies: adaptGroup20(raw["server.projectCopy"]),
  "server.project": adaptGroup21(raw["server.project"]),
  configDocument: adaptGroup22(raw["server.config-document"]),
  mcp: adaptGroup23(raw["server.mcp"]),
})

export const make = (options?: { readonly baseUrl?: URL | string }) =>
  HttpApiClient.make(ClientApi, options).pipe(Effect.map(adaptClient))
